# Generated by Django 4.2.11 on 2024-03-17 07:29

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_post_photo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, default=None, null=True, verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='post',
            name='video2',
            field=embed_video.fields.EmbedVideoField(blank=True, default=None, null=True, verbose_name='Видео 2'),
        ),
    ]
